### ISSUE TITLE
Auxiliary Rendering Tracker

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#49]
Tracker to help me keep track of which auxiliary renders I have confirmed rendering properly again
- [x] Contributor flowers
- [x] Phi's flower
- [x] Vazkii's twintails
- [x] haighyorkie's goldfish
- [x] mana tablets on belt
- [x] terrasteel helmet wills
- [ ] cosmetic baubles
  - [ ] bowtie
  - [ ] necktie
  - [ ] red glasses
  - [ ] fluffy scarf
  - [ ] engineer goggles
  - [ ] eyepatch
  - [ ] wicked eyepatch
  - [ ] red ribbons
  - [ ] pink flower bud
  - [ ] polka dot bows
  - [ ] blue butterfly
  - [ ] cat ears
  - [ ] witch pin
  - [ ] devil tail
  - [ ] kamui eye
  - [ ] googly eyes
  - [ ] four leaf clover
  - [ ] clock eye
  - [ ] unicorn horn
  - [ ] devil horns
  - [ ] hyper plus
  - [ ] botanist emblem
  - [ ] ancient mask
  - [ ] eerie mask
  - [ ] alien antenna
  - [ ] anaglyph glasses
  - [ ] orange shades
  - [ ] groucho glasses
  - [ ] thick eyebrows
  - [ ] lusitanic shield
  - [ ] tiny potato mask
  - [ ] questgiver mark
- [x] diva charm
- [x] flugel tiara
- [ ] golden laurel
- [x] cloak of virtue
- [x] cloak of sin
- [x] snowflake pendant
- [x] the spectator
- [x] tectonic girdle
- [x] pyroclast pendant
- [ ] monocle
- [x] crimson pendant
- [x] tiny planet
- [x] soujourner's/planestrider/globetrotter sash

**Comment by williewillus** [comment]
Reopening for 1.9
